define({root:{
    title: "Add Block Range",
    blockRangeFormLabel:"Block Range",
    blockRangeIdLabel: "ID:",
    locationFromLabel: "From:",
    locationToLabel: "To:",
    selectIntersectionTooltip: "Select Intersection",
    save: "Save",
    flipParity: "Flip Parity",
    flipGeometry: "Reverse Direction",
    previousPanel: "&lt; Back",
    nextPanel: "Next &gt;",
    networkItem: "${0} (${1})",
    routeIdLabel: "Route:",
    chooseRouteMenuItem: "Choose Route",
	  chooseRedlineMenuItem: "Choose Redline",
    chooseIntersection:"Choose Intersection",
    selectedRoutesMenuItem: "Selected Routes",
    highlightedRoutesMenuItem: "Highlighted Routes",
    selectRouteTooltip: "Select a Block Range",
    selectBlockRange:"Select a Block Range",
    fromMeasureFormLabel: "From",
    toMeasureFormLabel: "To",
    dateFormLabel: "Dates",
    fromDateLabel: "Start Date:",
    toDateLabel: "End Date:",
    useRouteStartDateLabel: "Use route start date",
    useRouteEndDateLabel: "Use route end date",
    routeStart: "Route start",
    routeEnd: "Route end",
    networkColumn: "Network",
    layerColumn: "Layer",
    attributeColumn: "Attribute",
    valueColumn: "Value",
    populateAttributes: "Copy Attribute Values",
    closeWarning:"There are unsaved changes in the widget, Do you want to close?",
    cancelWarning:" There are unsaved changes in the widget. Do you want to cancel the changes?",
    validation: {
        enterNumber: "Please enter a number.",
        enterNumberWithoutDecimal: "Please enter a number without any decimal.",
        enterStringLengthSingular: "Please enter at most ${0} character.",
        enterStringLengthPlural: "Please enter at most ${0} characters."
    },
    error: {
        correctErrors: "Please correct the highlighted attribute errors before saving.",
        intersectionError:"A block range intersection can only be modified to a new intersection if its on the same route and it falls inside the block range or on a neighboring gap",
        newBlockRangeError: "A new block range cannot be created since a partial block range is already present for this block.\n \n Please update the existing block range or delete an existing block range before adding a new one.",
        invalidRouteId: "Please enter a route ID.",
        invalidFromIntersection: "Please select a valid From Intersection",
        invalidToIntersection: "Please select a valid To Intersection",
        invalidRouteSelection: "Please select routes.",
        invalidNumericRouteId: "Please enter a valid numeric route ID.",
        invalidRouteResult: "The route could not be located. Please choose a valid route.",
        missingMeasures: "Please define the From and To measures.",
        invalidFromMeasure: "Please define a valid From measure.",
        invalidToMeasure: "Please define a valid To measure.",
        invalidFromToDates: "The End Date must occur after the Start Date.",
        routeMeasuresNull: "The route does not have measure values defined or the measures are invalid.",
        measuresNotTranslatableNoResults: "The measure values could not be translated across networks (LRMs).  There are no matching routes in the target network.",
        measureValidationError: "Unable to validate the measure values on the selected route.",
        measureTranslationError: "Unable to translate the measure values across networks.",
        noIncludedLayers: "Please include at least one event layer in the edit set.",
        saveError: "There was an error while saving the event record(s).\n\nDetail: ${0}",
        queryError: "Unable to perform the map query.",
        identifyError: "No attributes could be found.",
        getFeaturesError: "There was an error while getting the route information.",
        calculateMeasuresError: "Unable to get measures for all of the routes.",
        checkLocksError: "Unable to check locks for all of the routes.",
        noReferentMethodLayerName: "The point feature class you are offsetting from",
        noReferentMethod: "${0} was not found in the list of coded value domains for the dReferentMethod domain in your geodatabase.  In order to save an event offset from this point feature class, add a code and description for the point feature class to the list, reload the instance, and then add your event.",
        AcquireLocksSaveChangesError: "Unable to acquire locks for saving the edit(s). Please try again later.",
        AcquireLocksEditError: "Unable to acquire locks for editing. Please try again later."
    }
}});
